### ISSUE TITLE
Run must-gather in 'merge-results' mode

### ISSUE THREAD

**Issue by AsherShoshan** [openshift/must-gather#110]
When running must-gather via 'oc adm must-gather --image=...' , a new result folder is created.
Lots of static information (NS info, CRD's, Deployments, etc) is duplicated.
Need a way to runwith merge-results mode to have only the delta/aditional info.

Or an option to run must-gather with 'logs/events' mode - to produce only pod logs and events to be merged into a pre populated result folder.

**Comment by sferich888** [comment]
Does the output dir (see help with command) not do this for you?

**Comment by AsherShoshan** [comment]
But is it merging the data or overwitting (if I use --dest-dir flag)?
