### ISSUE TITLE
Emit highlevel copy/pasteable summary information 

### ISSUE THREAD

**Issue by sdodson** [openshift/must-gather#186]
I'd like for the console output of the `oc adm must-gather` command to include copy / pastable summary of the top pieces of data necessary. These should be the key pieces of information that we feel *every* single bug or case must include for highest level triage. Something like the following.

```
Output in must-gather-xyz.tar.gz

When opening a support case, bugzilla, or issue please include the following summary data along with any other requested information.
Cluster Version: 4.5.11
Platform: AWS
Degraded Operators: openshift-rocketship
```

**Comment by wking** [comment]
Bonus points for something that you can run on a stand-alone must-gather someone handed you, e.g. `oc adm must-gather analyze some-user-must-gather.tar.gz` that spits out the same summary/analysis.  One difficulty would be that the analysis would depend on the must-gather image, and pluggable images for must-gather _analysis_ seems like overkill...  But maybe core-OCP-must-gather is a special-enough case that it can have special local-Go analysis code?

**Comment by sferich888** [comment]
/remove-lifecycle rotten 

@rcbaus was looking at writing something for this. 
@cuppett you may also want to be aware of this because it connects to https://projects.engineering.redhat.com/browse/DR-1537 and https://projects.engineering.redhat.com/browse/DR-1539

**Comment by rcbaus** [comment]
My approach on the "something" that @sferich888 referred to, will be a command line tool independent of 'oc' itself, allowing a summary to be done on must-gather archive using a standalone binary and without needing to have oc or a cluster present. 

Having the ability to summarize the archive without any dependency other than a standalone binary and the archive is a beneficial one.

**Comment by sferich888** [comment]
https://github.com/openshift/oc/pull/738 would close this issue if completed.
