### ISSUE TITLE
RFE: Include pods and events information from all namespaces

### ISSUE THREAD

**Issue by oarribas** [openshift/must-gather#215]
Include pods and events information from all namespaces to the must-gather collection.
~~~
oc adm inspect --dest-dir must-gather pods --all-namespaces
oc adm inspect --dest-dir must-gather events --all-namespaces
~~~

**Comment by rutvik23** [comment]
For events, despite the fact that they would be removed after 3hours as per default event-ttl, I think this would be still too much for a Must_gather in terms of space to store events from all the namespaces especially when we encounter an environment where hundreds of namespaces being actively operated.
