### ISSUE TITLE
[RHOCP][4.6] Include missing Core namespace

### ISSUE THREAD

**Issue by vlours** [openshift/must-gather#216]
Hi guys,

Not sure if you aware of it, but since RHOCP4.6, some new namespaces have been added to the core, such as `openshift-*-infra`, `openshift-oauth-apiserver`.
And as those namespaces are now part of the RHOCP clusters, we need them as part of the must-gather to diagnose Red Hat Customers' issues.
I've been facing cases where I was looking at the must-gather, and then I had to request the `inspect ns/....` for the missing namespace.

Could you please add the missing namespaces to the must-gather gather list?

Cheers,

**Comment by rutvik23** [comment]
I see some of them are already included here https://github.com/openshift/must-gather/pull/209
