### ISSUE TITLE
Include insights-operator archive in must-gather

### ISSUE THREAD

**Issue by iNecas** [openshift/must-gather#255]
While insights-operator archive is significantly smaller than must-gather, it manages to collect data relevant for the cluster that are not collected by must-gather.

Having insights-operator as part of the must-gather would expand the data available for troubleshooting, either to be used directly, or by the recommendation engine for the support.

**Comment by sferich888** [comment]
@iNecas I added a PR for this; I will want @davemulford to review it; as I am worried that this method may need to be adjusted given the amount of data we can pull back doing this.
