### ISSUE TITLE
elide secret data from must-gather

### ISSUE THREAD

**Issue by phhutter** [openshift/must-gather#278]
Hi,

Is there a reason why must-gather includes some secrets by default? This default behavior also collect secrets from namespaces like the following:

(tested with oc cli 4.6.x)
./namespaces/openshift-authentication/core/secrets.yaml
./namespaces/openshift-config/core/secrets.yaml

These secrets.yaml usually contain ldap username and passwords.

I would prefer a toggle where we can explicitly enable a dump of any sensitive data like secrets/configmaps to prevent data leakage.
I know that another tool called must-gather-clear could remove sensitive data afterwards. But why shouldn't we change the default behavior to a minimum and add additional information, if really needed.

**Comment by josefkarasek** [comment]
@phhutter check out https://github.com/openshift/must-gather-clean
