### ISSUE TITLE
[RFE] Add the version of the branch to the version file

### ISSUE THREAD

**Issue by oarribas** [openshift/must-gather#314]
Most of the times, the `version` file (generated by the [version function](https://github.com/openshift/must-gather/blob/master/collection-scripts/version)) only shows "`4.0-art-dev`" or "`Unknown`", which is not very useful.
If it's not possible to get the version of the image used, at least the branch in this repo (and maybe the last commit applied) could be added to the output of the `version` function (`release-4.6`, `release-4.7`, `release-4.8`, `release-4.9`, `release-4.10`, ...).

**Comment by sferich888** [comment]
https://github.com/openshift/must-gather/pull/129 I think addresses this. 
Other improvements are being made with https://github.com/openshift/must-gather/pull/327

**Comment by oarribas** [comment]
@sferich888 , #129 is not addressing this, as the `version` file in latest must-gather versions is still not showing information about the version.

The `version` file in a must-gather from an OCP 4.11 cluster only shows `4.0-art-dev`:
```
$ oc version
Client Version: 4.11.9
Server Version: 4.11.9
Kubernetes Version: v1.24.0+dc5a2fd

$ cat version 
openshift/must-gather
4.0-art-dev
```

There is no info about the version of the must-gather image used to collect it.

**Comment by palonsoro** [comment]
A version obtained at the must-gather image will never reflect the version used to run `oc adm must-gather` command but the version of oc inside the must-gather image.

Writing that version doesn't have greatest value, because it is imposed by the cluster version (the must-gather image is derived from cli image of the same release, so oc version is imposed by the release).

If the client version is desired, this should be proposed and implemented in oc repo

**Comment by sferich888** [comment]
@palonsoro see https://github.com/openshift/must-gather/pull/327#issuecomment-1330827918

**Comment by oarribas** [comment]
This issue is not for the `oc` version used for running the command, but the version of the must-gather script used.
The current `version` script in the must-gather (https://github.com/openshift/must-gather/blob/release-4.11/collection-scripts/version) is not working properly and only shows `4.0-art-dev` (and not the digest of the image or anything else):
```
$ cat version 
openshift/must-gather
4.0-art-dev
```

/reopen
