### ISSUE TITLE
Gather the same information from OLM managed Operators as from ClusterOperators 

### ISSUE THREAD

**Issue by jlojosnegros** [openshift/must-gather#319]
## Current behaviour
Currently must-gather, using `oc adm inspect clusteroperators`, get the list of all the `ClusterOperator` objects and then traverse all their related resources collecting information about pods, logs, etc 

must-gather gets also some information about OLM, using `oc adm inspect -A olm` command, including the list of `Operator` objects, but it does not collect any other related resource information

## Desired behaviour
must-gather could collect the same information from `Operator` objects as is currently doing for `ClusterOperator` objects maybe using a new `oc adm inspect operators` command.

## Motivation

Openshift is heavily based on operators and not all of them are part of the vanilla system. 
must-gather is a very valuable tool for debugging purposes and helps a lot with troubleshooting but its information about OLM operators is not as good as it could be, making harder to detect and troubleshoot problems with these components even more in some business areas like TelCo, where the number of "non-vanilla" operators is increasing.

**Comment by sferich888** [comment]
@ecordell @dmesser can you all review this as a possible RFE with the OLM team to help with data collection/debugging of operators?

**Comment by sferich888** [comment]
@jlojosnegros what all do you want to collect? 
`oc adm inspect -A olm` only gets you the `ClusterServiceVersion` from all namespaces; and `ClusterServiceVersion` objects don't define any `.status.relatedObjects` thus not recursion/nested collection occurs when running inspect on that resource (and this is why you only get the CSV for each operator with the `oc adm inspect -A olm` command).

If the CSV told us something about the 'operator' and pointed us to an object that defined `.status.relatedObjects`  we might be able to extend [the OLM collection script](https://github.com/openshift/must-gather/blob/master/collection-scripts/gather_olm) to pull this information but we would need to know exactly what to collect at the top level. 

@kevinrizza or @awgreene what is the top level 'operator' object for operators installed by OLM?

**Comment by awgreene** [comment]
The resources collected by the OLM collection script today include any CRDs that are a part of the olm category, which includes:
- [ClusterServiceVersions](https://github.com/operator-framework/api/blob/b611f6cef49cb8c6d621145c4e31d8ddfd4c59f4/crds/operators.coreos.com_clusterserviceversions.yaml#L12)
- [Subscriptions](https://github.com/operator-framework/api/blob/b611f6cef49cb8c6d621145c4e31d8ddfd4c59f4/crds/operators.coreos.com_subscriptions.yaml#L12)
- [OperatorConditions](https://github.com/operator-framework/api/blob/b611f6cef49cb8c6d621145c4e31d8ddfd4c59f4/crds/operators.coreos.com_operatorconditions.yaml)
- [OLMConfigs](https://github.com/operator-framework/api/blob/b611f6cef49cb8c6d621145c4e31d8ddfd4c59f4/crds/operators.coreos.com_olmconfigs.yaml#L12)
- [InstallPlans](https://github.com/operator-framework/api/blob/b611f6cef49cb8c6d621145c4e31d8ddfd4c59f4/crds/operators.coreos.com_installplans.yaml#L12)
- [OperatorGroups](https://github.com/operator-framework/api/blob/b611f6cef49cb8c6d621145c4e31d8ddfd4c59f4/crds/operators.coreos.com_operatorgroups.yaml#L12)
- [CatalogSources](https://github.com/operator-framework/api/blob/b611f6cef49cb8c6d621145c4e31d8ddfd4c59f4/crds/operators.coreos.com_catalogsources.yaml#L12)
- [Operator CRs](https://github.com/operator-framework/api/blob/b611f6cef49cb8c6d621145c4e31d8ddfd4c59f4/crds/operators.coreos.com_operators.yaml#L12)

>If the CSV told us something about the 'operator' and pointed us to an object that defined .status.relatedObjects we might be able to extend [the OLM collection script](https://github.com/openshift/must-gather/blob/master/collection-scripts/gather_olm) to pull this information but we would need to know exactly what to collect at the top level.

The operator CR already keeps track of all resources related to the operator in it's [status.Components field](https://github.com/operator-framework/api/blob/b611f6cef49cb8c6d621145c4e31d8ddfd4c59f4/crds/operators.coreos.com_operators.yaml#L40).

It's worth mentioning that were moving towards a new set of APIs, where resources related to an operator will be described in the [bundle CR](https://github.com/operator-framework/rukpak/blob/c527e657b4dabfd228068fbe458b72acb013bf00/manifests/apis/crds/core.rukpak.io_bundles.yaml). The script could be updated to iterate over these resources once the transition is made.

**Comment by sferich888** [comment]
@ingvagabund I hat to keep bouncing this around; but I fundamentally think that this should be implemented at a layer 'lower' than the 'must-gather' collector. 

Should we move this request to an RFE for `oc adm inspect` to have it travers the [status.Components fields](https://github.com/operator-framework/api/blob/b611f6cef49cb8c6d621145c4e31d8ddfd4c59f4/crds/operators.coreos.com_operators.yaml#L40), when an operator CR is found? 

xref: https://github.com/openshift/oc/blob/master/pkg/cli/admin/inspect/resource.go#L36-L120 do we just need to add a case for this in this block of code?

**Comment by sferich888** [comment]
/close

We would like more information about exactly what it is people want to see collected as it pertains to OLM information, that isn't already collected.
