### ISSUE TITLE
[RFE] Adding the missing clusterresourcequota and Flowcontrol

### ISSUE THREAD

**Issue by vlours** [openshift/must-gather#407]
The Following Resources are missing in the Must-gather:

- clusterresourcequotas.quota.openshift.io
- prioritylevelconfigurations.flowcontrol.apiserver.k8s.io 
- flowschemas.flowcontrol.apiserver.k8s.io

That some unusual resources, but a miss configuration may have a big impact on the cluster performances.
Once added to the MG, we should be able to get them added in `omc` and `omg` for the support teams to check them.
And so I will be able to included them in my health check script to help review them quickly.

Happy to discuss it, if your think that we should not include them.

**Comment by sferich888** [comment]
@vlours  can this be closed? your PR merged!

**Comment by vlours** [comment]
@sferich888 Sorry I was on leave when this has been merged, and forgot about closing it.
Thanks for your help.
