### ISSUE TITLE
Request for Comprehensive Kubernetes Permissions to Execute 'oc adm must-gather' Command in OpenShift Pod

### ISSUE THREAD

**Issue by Lolelinus13** [openshift/must-gather#438]
Hello,

I am currently working on setting up the oc adm must-gather command to run within a pod in our OpenShift environment. To ensure that the ServiceAccount used by the pod has all the necessary permissions to execute the command successfully, I need a comprehensive list of the required Kubernetes permissions.

Could you please provide a detailed list of all the necessary Kubernetes permissions that are needed to run the oc adm must-gather command? This information will greatly help in configuring the appropriate Role or ClusterRole for the ServiceAccount.

Thank you for your assistance!

Best regards,
Lolelinus

**Comment by sferich888** [comment]
/close

I am going to close this as answered; if you have further questions let me know and I will try and answer them the best I can.
