### ISSUE TITLE
Errors don't align with reason for failure

### ISSUE THREAD

**Issue by sferich888** [openshift/must-gather#6]
Example:
```
$ bin/openshift-must-gather info clusteroperators
Error: the server doesn't have a resource type "clusteroperators"
```
is caused because the user's kubeconfig are not set and/or the active context is not authenticated with the cluster. 

We should provide a better error and/or things to try (like logging in) if something like this happens.

**Comment by juanvallejo** [comment]
Upstream PR: https://github.com/kubernetes/kubernetes/pull/73608

**Comment by juanvallejo** [comment]
We'll have to re-bump dependencies to pick up that fix. It has already made it into the cli-runtime repo: https://github.com/kubernetes/cli-runtime/commit/3d3b57cfe43cffbcef88581facc53b03aa7dcd67

**Comment by sferich888** [comment]
@sanchezl should we keep this open? 
@deads2k what are your thoughts?
