### ISSUE TITLE
Publish OCP Image

### ISSUE THREAD

**Issue by sanchezl** [openshift/must-gather#60]
Follow the [policies, guidelines, and standards](https://mojo.redhat.com/docs/DOC-1179058) to release an OCP image of the must-gather tool.
 
- [x] [Ensure image DistGit repository exists](https://mojo.redhat.com/docs/DOC-1168290)
  - [x] Request an [new build repository](https://comet.engineering.redhat.com/containers/repositories/create/build).
  - [x] Wait for new issue to appear in the [Release Engineering (RCM) JIRA](https://projects.engineering.redhat.com/projects/RCM/issues?filter=reportedbyme)
  - [x] RCM JIRA task completed.
- [x] [Create task in ART JIRA](https://jira.coreos.com/browse/ART-85) to have the image build managed by the automated release team. 
- [x] Add image to release payload
- [x] Add `must-gather` ImageStream to openshift-samples-operator.

**Comment by sanchezl** [comment]
![screenshot from 2019-02-18 12-41-05](https://user-images.githubusercontent.com/5381811/52968379-ff136a80-337a-11e9-8045-66406ebae93b.png)

**Comment by sanchezl** [comment]
Task opened in PnT JIRA: [RCM-51488](https://projects.engineering.redhat.com/browse/RCM-51488)

**Comment by sanchezl** [comment]
Task opened in ART JIRA: [ART-478](https://jira.coreos.com/browse/ART-478)

**Comment by sanchezl** [comment]
DistGit repository created: http://dist-git.host.prod.eng.bos.redhat.com/cgit/containers/ose-must-gather/

**Comment by deads2k** [comment]
@sanchezl what's our current state?

**Comment by sanchezl** [comment]
Image is now part of release image stream.
Also available via:
`docker pull quay.io/openshift-release-dev/ocp-v4.0-art-dev:v4.0.5-1-ose-must-gather`.

**Comment by sanchezl** [comment]
Opened https://github.com/openshift/cluster-samples-operator/pull/116

**Comment by sferich888** [comment]
@sanchezl can I run this on a 0.12 cluster install?
