### ISSUE TITLE
Move config.openshift.io out to its own plugin

### ISSUE THREAD

**Issue by sferich888** [openshift/must-gather#7]
We should restructure the commands / plugins so that config.openshift.io is its own plugin.

**Comment by sferich888** [comment]
@juanluisvaladas didn't we do this with https://github.com/openshift/must-gather/pull/22

**Comment by juanvallejo** [comment]
We added support for gathering data from multiple resources / multiple resource kinds at the same time with #22. We still gather config.openshift.io data as part of every command run, however

**Comment by sferich888** [comment]
I am going to close this as we plan to fix this with: https://github.com/openshift/must-gather/pull/35
